create table if not exists public.login_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  email text not null,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table public.login_logs enable row level security;

drop policy if exists "Users can insert own login logs" on public.login_logs;
create policy "Users can insert own login logs"
on public.login_logs
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can read own login logs" on public.login_logs;
create policy "Users can read own login logs"
on public.login_logs
for select
to authenticated
using (auth.uid() = user_id);
